// Mocks generated by Mockito 5.4.6 from annotations
// in ev_charging_finder/test/features/station_list/data/repositories/station_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:ev_charging_finder/features/station_list/data/datasources/station_remote_datasource.dart'
    as _i3;
import 'package:ev_charging_finder/features/station_list/data/models/station_search_response_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeStationSearchResponseModel_0 extends _i1.SmartFake
    implements _i2.StationSearchResponseModel {
  _FakeStationSearchResponseModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [StationRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockStationRemoteDataSource extends _i1.Mock
    implements _i3.StationRemoteDataSource {
  MockStationRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.StationSearchResponseModel> searchStations({
    required String? query,
    String? city,
    int? page = 1,
    int? pageSize = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchStations, [], {
              #query: query,
              #city: city,
              #page: page,
              #pageSize: pageSize,
            }),
            returnValue: _i4.Future<_i2.StationSearchResponseModel>.value(
              _FakeStationSearchResponseModel_0(
                this,
                Invocation.method(#searchStations, [], {
                  #query: query,
                  #city: city,
                  #page: page,
                  #pageSize: pageSize,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.StationSearchResponseModel>);
}
