// Mocks generated by Mockito 5.4.6 from annotations
// in ev_charging_finder/test/features/station_list/presentation/providers/station_search_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:ev_charging_finder/core/error/failures.dart' as _i6;
import 'package:ev_charging_finder/features/station_list/domain/station_repository.dart'
    as _i2;
import 'package:ev_charging_finder/features/station_list/domain/station_search_response.dart'
    as _i7;
import 'package:ev_charging_finder/features/station_list/domain/usecases/search_stations_usecase.dart'
    as _i3;
import 'package:fpdart/fpdart.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeStationRepository_0 extends _i1.SmartFake
    implements _i2.StationRepository {
  _FakeStationRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SearchStationsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchStationsUseCase extends _i1.Mock
    implements _i3.SearchStationsUseCase {
  MockSearchStationsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.StationRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeStationRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.StationRepository);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.StationSearchResponse>> call(
    _i3.SearchStationsParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i4.Future<
                  _i5.Either<_i6.Failure, _i7.StationSearchResponse>
                >.value(
                  _i8.dummyValue<
                    _i5.Either<_i6.Failure, _i7.StationSearchResponse>
                  >(this, Invocation.method(#call, [params])),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, _i7.StationSearchResponse>>);
}
