// Mocks generated by Mockito 5.4.6 from annotations
// in ev_charging_finder/test/features/auth/presentation/auth_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:ev_charging_finder/core/error/failures.dart' as _i5;
import 'package:ev_charging_finder/features/auth/domain/entities/user_entity.dart'
    as _i6;
import 'package:ev_charging_finder/features/auth/domain/repositories/auth_repository.dart'
    as _i2;
import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.UserEntity>> register({
    required String? email,
    required String? fullName,
    required bool? isGuest,
    required String? password,
    required String? phone,
    required String? role,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #email: email,
              #fullName: fullName,
              #isGuest: isGuest,
              #password: password,
              #phone: phone,
              #role: role,
            }),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i6.UserEntity>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i6.UserEntity>>(
                    this,
                    Invocation.method(#register, [], {
                      #email: email,
                      #fullName: fullName,
                      #isGuest: isGuest,
                      #password: password,
                      #phone: phone,
                      #role: role,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.UserEntity>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.UserEntity>> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i6.UserEntity>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i6.UserEntity>>(
                    this,
                    Invocation.method(#login, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.UserEntity>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.UserEntity>> getMe(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getMe, [token]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i6.UserEntity>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i6.UserEntity>>(
                    this,
                    Invocation.method(#getMe, [token]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.UserEntity>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.UserEntity>> updateProfile({
    required String? token,
    required String? fullName,
    required String? phone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #token: token,
              #fullName: fullName,
              #phone: phone,
            }),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i6.UserEntity>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i6.UserEntity>>(
                    this,
                    Invocation.method(#updateProfile, [], {
                      #token: token,
                      #fullName: fullName,
                      #phone: phone,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.UserEntity>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> logout({required String? token}) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [], {#token: token}),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#logout, [], {#token: token}),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}
